web/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('top/', include('top.urls')),
    path('invitation/', include('invitation.urls')),
    path('', auth_views.LoginView.as_view(template_name='invitation/login.html'), name='login'),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/invitation/urls.py
#-*- coding: utf-8 -*-

from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views


app_name = 'invitation'

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('<int:pk>', login_required(views.DetailView.as_view()), name='detail'),
    path('<int:pk>/cancel', login_required(views.cancel), name='cancel'),
    path('regist', login_required(views.regist), name='regist'),
    path('qr/<str:invitation_code>', views.show_invitation_code, name='show_invitation_code'),
    path('qr/check/<str:invitation_code>', views.check_invitation_code, name='check_invitation_code'),
]

web/top/urls.py
#-*- coding: utf-8 -*-

from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views


app_name = 'top'

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
]

web/invitation/models.py
#-*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.utils import dateformat, timezone

from staff.models import Staff

class Invitation(models.Model):
    """
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default='')
    body  = models.CharField(max_length=500, default='')
    schedule_datetime = models.DateTimeField(auto_now=False)
    cancel_flag = models.IntegerField(default=0)
    upd_datetime = models.DateTimeField(auto_now=True)
    ins_datetime = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        """
        """
        return self.title


class Client(models.Model):
    """
    """
    invitation = models.ForeignKey(Invitation, on_delete=models.CASCADE)
    invitation_code = models.CharField(max_length=100, default='', unique=True)
    name = models.CharField(max_length=100, default='')
    email = models.EmailField()
    is_checkin = models.IntegerField(default=0)
    upd_datetime = models.DateTimeField(auto_now=True)
    ins_datetime = models.DateTimeField(auto_now_add=True)    


    def __str__(self):
        """
        """
        return self.name

web/invitation/forms.py
#-*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User

from .models import Invitation, Client


class InvitationForm(forms.ModelForm):
    '''
    '''
    class Meta:
        model = Invitation

        fields = [
            'title',
            #'body',
            'schedule_datetime',
        ]

        error_messages = {
            'title': {
                'required': '必須です',
                'max_length': '100文字以内です',
            },
            #'body': {
            #    'required': '必須です',
            #    'max_length': '500文字以内です',
            #},
            'schedule_datetime': {
                'required': '必須です',
                'invalid': '日付/時間を正しく入力してください',
            },
        }


class InvitationClientForm(forms.ModelForm):
    '''
    '''
    class Meta:
        model = Client

        fields = [
            'name',
            'email',
        ]

        error_messages = {
            'name': {
                'required': '必須です',
                'max_length': '100文字以内です',
            },
            'email': {
                'required': '必須です',
                'invalid': '有効なメールアドレスを入力してください',
            },
        }

web/invitation/views.py
#-*- coding: utf-8 -*-

import json
import os
import urllib.parse

from django.conf import settings
from django.core.mail import get_connection, send_mail, EmailMessage, EmailMultiAlternatives
from django.http.response import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import generic

import boto3
import requests
from twilio.rest import Client as TwilioClient

from staff.models import Staff

from .application import InvitationRegistApp
from .defines import HOURS, MINUTES
from .forms import InvitationForm, InvitationClientForm
from .models import Invitation, Client
from .utils import make_invitation_codes


# Create your views here.
class IndexView(generic.ListView):

    template_name = 'invitation/index.html'
    context_object_name = 'invitation_datas'

    paginate_by = 10

    def get_context_data(self, **kwargs):
        """
        """
        context = super().get_context_data(**kwargs)

        get_query = {}
        
        for key in self.request.GET:
            if 'page' == key:
                pass
            elif 'staff' == key:
                try:
                    get_query.setdefault(key, int(self.request.GET[key]))
                except(ValueError):
                    get_query.setdefault(key, '')
            else:
                get_query.setdefault(key, self.request.GET[key])

        context['get'] = get_query
        context['query_string'] = urllib.parse.urlencode(get_query)

        context['HOURS'] = HOURS
        context['MINUTES'] = MINUTES
        
        staffs = Staff.objects.all().order_by('id')
        context['staffs'] = staffs

        return context
    
    def get_queryset(self):
        """Return the last five published questions.
        """
        invitations = Invitation.objects.all().order_by('id')

        if self.request.GET.get('title'):
            invitations = invitations.filter(title__contains=self.request.GET.get('title'))

        if self.request.GET.get('staff'):
            invitations = invitations.filter(user__staff__id=self.request.GET.get('staff'))

        if self.request.GET.get('start_schedule_datetime_date', '') and \
           self.request.GET.get('start_schedule_datetime_hour', '') and \
           self.request.GET.get('start_schedule_datetime_minute', ''):
            start_schedule_datetime = '{0} {1}:{2}:00'.format(
                self.request.GET.get('start_schedule_datetime_date', ''),
                self.request.GET.get('start_schedule_datetime_hour', ''),
                self.request.GET.get('start_schedule_datetime_minute', ''))
            invitations = invitations.filter(schedule_datetime__gte=start_schedule_datetime)

        if self.request.GET.get('end_schedule_datetime_date', '') and \
           self.request.GET.get('end_schedule_datetime_hour', '') and \
           self.request.GET.get('end_schedule_datetime_minute', ''):
            end_schedule_datetime = '{0} {1}:{2}:00'.format(
                self.request.GET.get('end_schedule_datetime_date', ''),
                self.request.GET.get('end_schedule_datetime_hour', ''),
                self.request.GET.get('end_schedule_datetime_minute', ''))
            invitations = invitations.filter(schedule_datetime__lte=end_schedule_datetime)

        return invitations


class DetailView(generic.DetailView):

    model = Invitation
    template_name = 'invitation/detail.html'


def regist(request):
    """
    """
    app = InvitationRegistApp(request)

    if 'POST' == request.method:

        data = app.exec()

        if 'ok' == data['result']:
            return HttpResponseRedirect(reverse('invitation:index'))

    else:
        data = app.get_default_data_set()

    data['HOURS'] = HOURS
    data['MINUTES'] = MINUTES
    
    return render(request, 'invitation/regist.html', data)
    

def cancel(request, pk):
    """
    """
    if 'POST' == request.method:
        invitation = get_object_or_404(Invitation, pk=pk)
        invitation.cancel_flag = 1
        invitation.save()

        with get_connection() as connection:

            for client in invitation.client_set.all():

                body = render_to_string('invitation/cancel_mail.txt', {
                    'client_name': client.name,
                    'title': invitation.title,
                    'schedule_datetime': invitation.schedule_datetime,
                })

                message = EmailMessage(invitation.title, body, settings.EMAIL_HOST_USER, [client.email], connection=connection)

                message.send()
          
    return HttpResponseRedirect(reverse('invitation:index'))


def show_invitation_code(request, invitation_code):
    """
    """
    img_path = os.path.join(settings.QRCODE_PATH, invitation_code + '.png')

    f = open(img_path, 'rb')

    return HttpResponse(f.read(), content_type='image/png')
    

def check_invitation_code(request, invitation_code):
    """
    """
    try:
        client = Client.objects.filter(invitation_code=invitation_code)[0]

        invitation = client.invitation
    
        #tell = client.invitation.user.staff.tell.replace('-', '')

        body = """
{} の件で、{} 様がお越しになりました。
2F エントランスまでお迎えに上がってください。
""".format(invitation.title, client.name)

        if 0 == client.is_checkin:

            # amazon sns
            #sns = boto3.client("sns")
            #message_attributes = {
            #    'AWS.SNS.SMS.SenderID': {
            #        'DataType': 'String',
            #        'StringValue': 'northshore' # 通知者表示に使用される送信者ID
            #    }
            #}
            #sns.publish(PhoneNumber="+81" + tell, Message=body, MessageAttributes=message_attributes)

            # slack
            params = {
                'token'  : settings.SLACK_TOKEN,
                'channel': settings.SLACK_CHANNEL,
                'text'   : "<!channel> " + body,
            }

            session = requests.Session()

            session.post(settings.SLACK_URL, data=params)

            client.is_checkin = 1

            client.save()

        return JsonResponse({'result': 'ok'})

    except IndexError:
        return JsonResponse({'result': 'error', 'message': 'データが存在しません'})

web/invitation/templates/invitation/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <meta charaset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <title>メカマーチャン</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link href="{% static '/css/common.css' %}" rel="stylesheet"/>
  {% block css %}{% endblock %}
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top"><a href="{% url 'top:index' %}" class="navbar-brand">メカマーチャン</a>
      <button type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>
    </nav>
    {% block contents %}{% endblock %}
    {% block js %}{% endblock %}
  </body>
</html>

web/invitation/templates/invitation/detail.html
{% extends "invitation/base.html" %}
{% load static %}
{% block css %}
<link href="{% static '/css/edit.css' %}" rel="stylesheet"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}
{% block contents %}
<div role="main" class="container">
  <h2>来社管理</h2>
  <form method="POST" action="{% url 'invitation:cancel' invitation.id %}" id="invitation_cancel_form" class="form">
    <h2>来社予定日時</h2>
    <table class="table table-bordered">
      {% comment %}
      <tr>
        <td scope="row" style="width: 30%">ステータス</td>
        <td>来社待ち</td>
      </tr>
      {% endcomment %}
      <tr>
        <td scope="row" style="width: 30%">予定日時</td>
        <td>{{invitation.schedule_datetime}}</td>
      </tr>
    </table>
    {% comment %}<h2>理由</h2>{% endcomment %}
    <table class="table table-bordered">
      <tr>
        <td scope="row" style="width: 30%">来社理由</td>
        <td>{{invitation.title}}</td>
      </tr>
      {% comment %}
      <tr>
        <td scope="row">本文</td>
        <td>{{invitation.body}}</td>
      </tr>
      {% endcomment %}
    </table>
    <h2>お客様</h2>
    {% for c in invitation.client_set.all %}
    <table class="table table-bordered">
      {% if c.is_checkin %}
      <tr>
        <td scope="row" style="width: 30%"  colspan="2"><span class="badge badge-pill badge-success">チェックイン済み</span></td>
      </tr>
      {% endif %}
      <tr>
        <td scope="row" style="width: 30%">名前</td>
        <td>{{c.name}}</td>
      </tr>
      <tr>
        <td scope="row">メールアドレス</td>
        <td>{{c.email}}</td>
      </tr>
    </table>
    {% endfor %}
    {% csrf_token %}
    <button onClick="location.href='{% url 'invitation:index' %}'; return false;" class="btn btn-sm btn-warning">一覧に戻る</button>
    <span class="float-xl-right">
      {% if invitation.cancel_flag == 1 %}
      <button type="button" class="btn btn-sm btn-danger">キャンセル済</button>
      {% else %}
      <button class="btn btn-sm btn-danger" id="invitation_cancel">キャンセル</button>
      {% endif %}
    </span>
  </form>
</div>
{% endblock %}
{% block js %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static '/js/invitation-cancel.js' %}"></script>
{% endblock %}

web/invitation/templates/invitation/index.html
{% extends "invitation/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}
{% block contents %}
<div role="main" class="container">
  <h2>来社管理</h2>
  <form method="GET" action="{% url 'invitation:index' %}">
    <table class="table">
      <tbody>
        <tr>
          <th scope="col">予定日時</th>
          <td scope="col">
            <div class="form-inline">
              <div class="form-group">
                <input type="text" name="start_schedule_datetime_date" value="{{get.start_schedule_datetime_date}}" class="form-control datepicker"/>&nbsp;&nbsp;&nbsp;
	      </div>
              <div class="form-group">
                <select name="start_schedule_datetime_hour" class="form-control">
                  <option value="">-----</option>
                  {% for i in HOURS %}
                  <option value="{{i}}" {% if get.start_schedule_datetime_hour == i %}selected{% endif %}>{{i}}</option>
                  {% endfor %}
                </select>
                &nbsp;&nbsp;時&nbsp;&nbsp;
              </div>
              <div class="form-group">
                <select name="start_schedule_datetime_minute" class="form-control">
                  <option value="">-----</option>
                  {% for i in MINUTES %}
                  <option value="{{i}}" {% if get.start_schedule_datetime_minute == i %}selected{% endif %}>{{i}}</option>
                  {% endfor %}
                </select>
                &nbsp;&nbsp;分&nbsp;&nbsp;
              </div>
	      &nbsp;&nbsp;〜&nbsp;&nbsp;
              <div class="form-group">
                <input type="text" name="end_schedule_datetime_date" value="{{get.end_schedule_datetime_date}}" class="form-control datepicker"/>&nbsp;&nbsp;&nbsp;
	      </div>
              <div class="form-group">
                <select name="end_schedule_datetime_hour" class="form-control">
                  <option value="">-----</option>
                  {% for i in HOURS %}
                  <option value="{{i}}" {% if get.end_schedule_datetime_hour == i %}selected{% endif %}>{{i}}</option>
                  {% endfor %}
                </select>
                &nbsp;&nbsp;時&nbsp;&nbsp;
              </div>
              <div class="form-group">
                <select name="end_schedule_datetime_minute" class="form-control">
                  <option value="">-----</option>
                  {% for i in MINUTES %}
                  <option value="{{i}}" {% if get.end_schedule_datetime_minute == i %}selected{% endif %}>{{i}}</option>
                  {% endfor %}
                </select>
                &nbsp;&nbsp;分&nbsp;&nbsp;
              </div>
            </div>
	  </td>
	</tr>
        <tr>
          <th scope="col">タイトル</th>
          <td scope="col"><input type="text" name="title" value="{{get.title}}" class="form-control"></td>
        </tr>
        <tr>
          <th scope="col">担当者</th>
          <td scope="col">
	    <select name="staff">
              <option value="">-----</option>
              {% for staff in staffs %}
              <option value="{{staff.user.id}}" {% if get.staff == staff.user.id %}selected{% endif %}>{{staff.user.username}}</option>
              {% endfor %}
            </select>
          </td>
        </tr>
      </tbody>
    </table>
    <div style="margin-bottom: 10px;">
      <button class="btn btn-sm btn-primary">検索</button>
    </div>
  </form>
  
  <div style="margin-bottom: 10px;" class="float-xl-right">
    <button onClick="location.href='{% url 'invitation:regist' %}'" class="btn btn-sm btn-primary">新規追加</button>
  </div>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">タイトル</th>
        <th scope="col">来社代表者</th>
        <th scope="col">来社予定時間</th>
        <th scope="col">作成者</th>
        <th scope="col">作成日</th>
      </tr>
    </thead>
    <tbody>
      {% for i in invitation_datas %}
      <tr {% if i.cancel_flag == 1 %}class="bg-light"{% endif %}>
        <td scope="row"><a href="{% url 'invitation:detail' i.id %}">{{i.title}}</a></td>
        <td>{{i.client_set.filter.0}}</td>
        <td>{{i.schedule_datetime}}</td>
        <td>{{i.user.username}}</td>
        <td>{{i.ins_datetime}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a href="?{{query_string}}&page={{ page_obj.previous_page_number }}" aria-label="Previous" class="page-link"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
      {% endif %}
      {% for i in paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}active{% endif %}" ><a href="?{{query_string}}&page={{i}}" class="page-link">{{ i }}</a></li>
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a href="?{{query_string}}&page={{ page_obj.next_page_number }}" aria-label="Next" class="page-link"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% endblock %}
{% block js %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static '/js/invitation-regist.js' %}"></script>
{% endblock %}

web/invitation/templates/invitation/login.html
{% extends "invitation/base.html" %}
{% load static %}
{% block css %}
<link href="{% static '/css/sign.css' %}" rel="stylesheet"/>
{% endblock %}
{% block contents %}
<div role="main" class="container">
  <form method="POST" action="{% url 'login' %}" class="form-signin">
    <h3 class="form-signin-heading">ログイン</h3>
    <label for="inputEmail" class="sr-only">ID</label>
    <input id="inputEmail" type="id" placeholder="ID" name="username" class="form-control"/>
    <label for="inputPassword" class="sr-only">Password</label>
    <input id="inputPassword" type="password" placeholder="Password" name="password" class="form-control"/>
    {% if form.errors %}
    <p class="error">ユーザ名/パスワードが不正です</p>
    {% endif %}
    <button type="submit" class="btn btn-lg btn-primary btn-block">ログイン</button>
      {% csrf_token %}
  </form>
</div>
{% endblock %}

web/invitation/templates/invitation/mail.html
<html lang="ja">
  <meta charaset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <link href="https://entrance.fukazawasoftwaredevelopment.com/static/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="https://entrance.fukazawasoftwaredevelopment.com/static/css/common.css" rel="stylesheet"/>
  <link href="https://entrance.fukazawasoftwaredevelopment.com/static/css/edit.css" rel="stylesheet"/>
  <body>
    <div role="main" class="container">
      <p>
	{{client_name}} 様 <br/><br/>
	{{title}} の件にて、<br/>
	{{schedule_datetime}} までに弊社にお越しください。<br/><br/>
	エントランスにつきましたら、iPadに以下のQRコードをご提示ください。<br/><br/><br/>
	<img src="{{qrcode}}"/>
      </p>
    </div>
  </body>
</html>

web/invitation/templates/invitation/regist.html
{% extends "invitation/base.html" %}
{% load static %}
{% block css %}
<link href="{% static '/css/edit.css' %}" rel="stylesheet"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}
{% block contents %}
<div role="main" class="container">
  <h2>来社管理</h2>
  <form method="POST" action="" class="form">
    <h2>来社予定日時</h2>
    <table class="table table-bordered">
      {% comment %}
      <tr>
        <td scope="row" style="width: 30%">ステータス</td>
        <td>来社待ち</td>
      </tr>
      {% endcomment %}
      <tr>
        <td scope="row" style="width: 30%"><p class="require">※予定日時</p></td>
        <td>
	  <div class="form-inline">
	    <div class="form-group">
              <input type="text" name="schedule_datetime_date" value="{{invitation_form.data.schedule_datetime_date}}" class="form-control datepicker"/>&nbsp;&nbsp;&nbsp;
	    </div>
	    <div class="form-group">
	      <select name="schedule_datetime_hour" class="form-control">
		<option value="">-----</option>
		{% for i in HOURS %}
                <option value="{{i}}" {% if invitation_form.data.schedule_datetime_hour == i %}selected{% endif %}>{{i}}</option>
		{% endfor %}
	      </select>
	      &nbsp;&nbsp;時&nbsp;&nbsp;
	    </div>
	    <div class="form-group">
	      <select name="schedule_datetime_minute" class="form-control">
		<option value="">-----</option>
		{% for i in MINUTES %}
                <option value="{{i}}" {% if invitation_form.data.schedule_datetime_minute == i %}selected{% endif %}>{{i}}</option>
		  {% endfor %}
	      </select>
	      &nbsp;&nbsp;分&nbsp;&nbsp;
	    </div>
	  </div>
	  {% if error_messages.schedule_datetime %}<p class="error">{{error_messages.schedule_datetime|escape}}</p>{% endif %}
        </td>
      </tr>
    </table>
    {% comment %}<h2>理由</h2>{% endcomment %}
    <table class="table table-bordered">
      <tr>
        <td scope="row" style="width: 30%"><p class="require">※来社理由</p></td>
        <td>
          <input id="inputTitleJp" type="text" name="title" value="{{invitation_form.data.title}}" placeholder="" class="form-control"/>
	  {% if error_messages.title %}<p class="error">{{error_messages.title|escape}}</p>{% endif %}
        </td>
      </tr>
      {% comment %}
      <tr>
        <td scope="row"><p class="require">※本文</p></td>
        <td>
          <textarea id="inputBodyJp" name="body" class="form-control">{{invitation_form.data.body}}</textarea>
	  {% if error_messages.body %}<p class="error">{{error_messages.body|escape}}</p>{% endif %}
        </td>
      </tr>
      {% endcomment %}
    </table>

    <h2>お客様</h2>
    <div id="clients">
      {% for client_form in client_forms %}
      <table class="table table-bordered">
	<tr>
          <td scope="row" style="width: 30%"><p class="require">※名前</p></td>
          <td>
            <input id="inputName{{forloop.counter0}}" type="text" name="name" value="{{client_form.data.name}}" placeholder="" class="form-control"/>
            {% if error_messages.name %}{% for error in error_messages.name %}{% if forloop.parentloop.counter0 == forloop.counter0 and error%}<p class="error">{{error|escape}}</p>{% endif %}{% endfor %}{% endif %}
          </td>
 	</tr>
	<tr>
          <td scope="row"><p class="require">※メールアドレス</p></td>
          <td>
            <input id="inputMail{{forloop.counter0}}" type="text" name="email" value="{{client_form.data.email}}" placeholder="" class="form-control"/>
            {% if error_messages.email %}{% for error in error_messages.email %}{% if forloop.parentloop.counter0 == forloop.counter0 and error%}<p class="error">{{error|escape}}</p>{% endif %}{% endfor %}{% endif %}
          </td>
	</tr>
	{% if not forloop.first %}
	<tr>
          <td scope="row"></td>
          <td><span class="float-xl-right"><button type="button" class="btn btn-sm btn-danger delete_client_buttons">削除</button></span></td>
	</tr>
	{% endif %}
      </table>
      {% endfor %}
    </div>

    <div>
      <span class="float-xl-right"><button type="button" class="btn btn-sm btn-primary" id="add_client_button">お客様追加</button></span>
      <br/><br/><br/>
    </div>

    {% csrf_token %}
    <div>
    <button onClick="location.href='{% url 'invitation:index' %}'; return false;" class="btn btn-sm btn-warning">一覧に戻る</button>
    <span class="float-xl-right">
      <button type="submit" class="btn btn-sm btn-primary">登録</button>
    </span>
    {% comment %}
    <button type="submit" class="btn btn-sm btn-danger">削除</button>
    <button type="submit" class="btn btn-sm btn-primary">変更</button>
    {% endcomment %}
    <div>
  </form>
</div>
{% endblock %}
{% block js %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static '/js/invitation-regist.js' %}"></script>
{% endblock %}